default_platform(:ios)

platform :ios do

  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store(
      username: ENV['APPLE_ID'],
      app_identifier: ENV['DEVELOPER_APP_ID']
    )
  end
  
  lane :beta do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(
      username: ENV['APPLE_ID'],
      app_identifier: ENV['DEVELOPER_APP_ID']
    )
  end
end