# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    # api_key = app_store_connect_api_key(
    #   key_id: "GF4U52P45A",
    #   issuer_id: "6053b7fe-68a8-4acb-89be-165aa6465141",
    #   key_filepath: "/Users/jang-yuncheol/Desktop/Devolop/center_monitor/ios/private_keys/AuthKey_GF4U52P45A.p8",
    #   duration: 500, # optional (maximum 1200)
    #   in_house: false # optional but may be required if using match/sigh
    # )

    # increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store(
      username: "optilo03031@gmail.com",
      password: "your_app_specific_password",  # 앱 암호 직접 입력
      app_identifier: "net.optilo.thermotrack",
      skip_screenshots: true,  # 스크린샷 업로드 생략 (선택 사항)
      # skip_metadata: true      # 메타데이터 업로드 생략 (선택 사항)
    )
  end
  
  lane :beta do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(
      username: ENV['APPLE_ID'],
      app_identifier: ENV['DEVELOPER_APP_ID']
      skip_waiting_for_build_processing: true, # 빌드 처리 대기 생략 (선택 사항)
    )
  end
end