# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android) 

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end 

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean bundleRelease") # APK 대신 AAB 빌드
    upload_to_play_store(
      json_key_data: "./play-store-api.json",
      track: "internal",
      # aab: "../build/app/outputs/bundle/release/app-release.aab" # ✅ 절대 경로 사용
      aab: "/Users/jang-yuncheol/Desktop/Devolop/center_monitor/build/app/outputs/bundle/release/app-release.aab", # ✅ 절대 경로 사용
      version_code: 10  # 🚨 버전 코드 강제 지정
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean bundleRelease") # APK 대신 AAB 빌드
    upload_to_play_store(
      json_key_file: "./play-store-api.json",
      track: "internal",
      aab: "/Users/jang-yuncheol/Desktop/Devolop/center_monitor/build/app/outputs/bundle/release/app-release.aab" # ✅ 절대 경로 사용
    )
  end
end
