default_platform(:android) 

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end  

  desc "Production Distribution"
  lane :deploy do
    # gradle(task: "clean bundleRelease") 
    upload_to_play_store(  
      json_key: "play-store-api.json",
      track: "production",
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end

  desc "Inner Distribution"
  lane :beta do
    # gradle(task: "clean bundleRelease") 
    upload_to_play_store(
      json_key: "./play-store-api.json",
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
end
