name: Flutter CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  build_and_deploy:
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: center_monitor  # 추가: 폴더 경로 지정

      - name: Clean Project
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      # Android Build & Deployment
      - name: Restore Keystore & Create `key.properties`
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "$KEYSTORE_FILE" | base64 --decode > android/app/keystore.jks
          echo "storeFile=keystore.jks" > android/app/key.properties
          echo "storePassword=$KEYSTORE_PASSWORD" >> android/app/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/app/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/app/key.properties
          
      - name: Create Play Store API JSON
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          echo "${{ secrets.GOOGLE_PLAY_API_KEY_JSON }}" | base64 --decode > android/play-store-api.json

      # - name: Create `local.properties`
      #   run: |
      #     echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      #     echo "flutter.sdk=$HOME/desktop/Devolop/flutter" >> android/local.properties
      - name: Build APK
        run: flutter build appbundle --release
      
      - name: Show `local.properties` File
        run: cat android/local.properties

      - name: List Build Outputs
        run: ls -R build/app/outputs/bundle/release/app-release.aab

      - name: Deploy to Play Store (Android)
        if: github.ref == 'refs/heads/dev'
        run: |
          cd android
          fastlane beta --verbose

      # iOS Build & Deployment
      - name: Build iOS App
        run: flutter build ipa --release

      - name: Export Secrets as Environment Variables
        run: |
          echo "APP_STORE_PASSWORD=${{ secrets.APP_STORE_PASSWORD }}" >> $GITHUB_ENV

      - name: Deploy to App Store (iOS)
        if: github.ref == 'refs/heads/dev'
        run: |
          cd ios
          fastlane beta
