name: Flutter CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  build_and_deploy:
    runs-on: [self-hosted, macOS, ARM64]
    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APP_STORE_PASSWORD: ${{ secrets.APP_STORE_PASSWORD }}
      DEVELOPER_APP_ID: ${{ secrets.DEVELOPER_APP_ID }}
      ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clean and Get Dependencies
        run: |
          flutter clean
          flutter pub get

      # - name: Show Pubspec File
      #   run: |
      #     cat pubspec.yaml  # ✅ pubspec.yaml 내용 출력

      - name: Restore Keystore & Create `key.properties`
        run: |
          echo "$KEYSTORE_FILE" | base64 --decode > android/app/keystore.jks
          echo "storeFile=keystore.jks" > android/app/key.properties
          echo "storePassword=$KEYSTORE_PASSWORD" >> android/app/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/app/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/app/key.properties

      - name: Create Play Store API JSON
        run: |
          echo "${{ secrets.GOOGLE_PLAY_API_KEY_JSON }}" | base64 --decode > android/play-store-api.json

      - name: Build APK
        run: flutter build appbundle --release

      - name: Deploy to Play Store (Android)
        if: github.ref == 'refs/heads/dev'
        run: |
          cd android
          fastlane beta 

      # iOS Build & Deployment
      - name: Build iOS App
        run: flutter build ipa --release

      - name: Export Secrets as Environment Variables
        run: |
          echo "APP_STORE_PASSWORD=${{ secrets.APP_STORE_PASSWORD }}" >> $GITHUB_ENV

      - name: Deploy to App Store (iOS)
        if: github.ref == 'refs/heads/dev'
        run: |
          cd ios
          fastlane beta
