name: Flutter CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build_and_deploy:
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clean and Get Dependencies
        run: |
          flutter clean
          flutter pub get

      # - name: Restore Keystore & Create `key.properties`
      #   run: |
      #     echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > android/app/keystore.jks
      #     echo "storeFile=keystore.jks" > android/app/key.properties
      #     echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/app/key.properties
      #     echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/app/key.properties
      #     echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/app/key.properties

      # - name: Create Play Store API JSON
      #   run: |
      #     echo "${{ secrets.GOOGLE_PLAY_API_KEY_JSON }}" | base64 --decode > android/play-store-api.json

      # - name: Build APK
      #   run: flutter build appbundle --release

      # - name: Deploy to Play Store (Android)
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     cd android
      #     fastlane deploy 

      # iOS Build & Deployment
      - name: Build iOS App
        run: flutter build ipa --release

      - name: Export Secrets as Environment Variables
        run: |

      - name: Export Secrets as Environment Variables
        run: |
          echo "DEVELOPER_APP_ID=${{ secrets.DEVELOPER_APP_ID }}" >> $GITHUB_ENV
          echo "APPLE_ID=${{ secrets.APPLE_ID }}" >> $GITHUB_ENV
          echo "ITC_TEAM_ID=${{ secrets.ITC_TEAM_ID }}" >> $GITHUB_ENV
          echo "TEAM_ID=${{ secrets.TEAM_ID }}" >> $GITHUB_ENV
          echo "FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}" >> $GITHUB_ENV


      - name: Deploy to App Store (iOS)
        if: github.ref == 'refs/heads/main'
        run: |
          cd ios
          fastlane beta
